apiVersion: v1
kind: Service
metadata:
  name: nginx-demo
spec:
  selector:
    app: nginx-demo
  ports:
    - port: 80
      targetPort: 80
      # nodePort optional (30000–32767); omit to auto-assign
  type: NodePort
